name: aParticles
main: Anon\aParticles
version: 1.1.0
api: [3.0.0, 3.0.0-ALPHA2]
author: Anon
website: www.google.com

commands:
  p:
    default: op
    description: Uso de particulas
    permission: aprt.use

permissions:
  aprt:
    default: false
    children:
      aprt.use:
        default: false
        description: Para ver la lista de commandos /p